spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/yadavro/server-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#          search-locations: "file:///C://Users//rohit//Documents//microservices//config"
#          search-loactions: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "ADMIN@123"
server:
  port: 8071