spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/yadavro/server-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#          search-locations: "file:///C://Users//rohit//Documents//microservices//config"
#          search-loactions: "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "ADMIN@123"
server:
  port: 8071